name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build -t dictionary .
    - name: Build test
      run: docker build -t test .
    - name: Run tests
      run: docker run test
      
 # docker_push:
  #  runs-on: ubuntu-latest
  #  steps:
  ##    - run: docker login -username ${{ secrets.DOCKER_USERNAME }} -password ${{ secrets.DOCKER_PASSWORD }} |
   #       docker push $ {{secrets.DOCKER_USERNAME}}/
      
  codestyle_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: codestyle_check
        uses: CyberZHG@github-action-python-lint@master
      
        
    env:
      GITHUB_TOKEN: ${{secrets.GIT_TOKEN }}
