name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build -t dictionary .
    - name: Build test
      run: docker build -t test .
    - name: Run tests
      run: docker run test
      
  docker_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2     
      - name: build image 
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dictionary . 
      - name: jopa  
        run: docker ps
      - name: docker push        
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
          docker push ${{secrets.DOCKER_USERNAME}}/dictionary
     
  codestyle_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: codestyle_check
        uses: CyberZHG/github-action-python-lint@master
      - name: get update
        run: sudo apt-get update -y
      - name: get install
        run: sudo apt-get install -y cppcheck
      - name: check
        run: cppcheck cppcheck -q --enable=all ./dictionary.cpp
      
        
    env:
      GITHUB_TOKEN: ${{secrets.GIT_TOKEN }}
