name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build -t dictionary .
    - name: Build test
      run: docker build -t test .
    - name: Run tests
      run: docker run test
      
  codestyle_check:
    runs-on: ubuntu-latest
    steps:
      - name: codestyle_check
        uses: smay1613/clang-tidy-action@master
      
        
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
